// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPWOecKFnnY9QIjite7n0A45hkD2nz7eg',
    appId: '1:1094783952092:web:dfba8c8354797b1d208019',
    messagingSenderId: '1094783952092',
    projectId: 'uatizapi2-ded6f',
    authDomain: 'uatizapi2-ded6f.firebaseapp.com',
    storageBucket: 'uatizapi2-ded6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkYSxY098CLEl4F-h8lGzdvv4qlQGSNVo',
    appId: '1:1094783952092:android:0f886fa91a9143f8208019',
    messagingSenderId: '1094783952092',
    projectId: 'uatizapi2-ded6f',
    storageBucket: 'uatizapi2-ded6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdm_AQopCI_Unz4qtDxhURSMxLuVrkjHQ',
    appId: '1:1094783952092:ios:0ba6dadbbd3cf71e208019',
    messagingSenderId: '1094783952092',
    projectId: 'uatizapi2-ded6f',
    storageBucket: 'uatizapi2-ded6f.firebasestorage.app',
    iosBundleId: 'com.example.zapizapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdm_AQopCI_Unz4qtDxhURSMxLuVrkjHQ',
    appId: '1:1094783952092:ios:0ba6dadbbd3cf71e208019',
    messagingSenderId: '1094783952092',
    projectId: 'uatizapi2-ded6f',
    storageBucket: 'uatizapi2-ded6f.firebasestorage.app',
    iosBundleId: 'com.example.zapizapi',
  );
}
